version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install pyinstaller
  build:
    commands:
      - cd game
      - pyinstaller --onefile game.py
  post_build:
    commands:
      - aws s3 cp dist/game s3://yourbucket/game

artifacts:
  files:
    - game/dist/game
